In [41]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction import DictVectorizer
from sklearn import preprocessing, model_selection

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.naive_bayes import MultinomialNB

In [2]:
path = 'data/restaurants_laptop_train_with_pos.csv'

df = pd.read_csv(path)
df.head()


num   text    pos aspect_tag  polarity
0  s_1    But  CCONJ        NAT         0
1  s_1    the    DET        NAT         0
2  s_1  staff   NOUN         AT        -1
3  s_1    was    AUX        NAT         0
4  s_1     so    ADV        NAT         0

In [32]:
encoder = DictVectorizer(sparse=False)
le = preprocessing.LabelEncoder()

X = df.drop(columns=['aspect_tag','polarity'])
X = encoder.fit_transform(X.to_dict().values)
y = df.aspect_tag.values
y = le.fit_transform(y)
print('Classes: {}'.format(le.classes_))


X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size = 0.2, random_state=42)
X_train.shape, y_train.shape

Classes: ['AT' 'NAT']


((27526, 6298), (27526,))

In [38]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

C:\Users\calvi\anaconda3\envs\CS4248_python\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [39]:
pred = lr.predict(X_test)
pred, y_test

(array([1, 0, 1, ..., 1, 1, 1]), array([1, 0, 1, ..., 1, 1, 1]))

In [40]:
print('Testing accuracy: {:.2f}%'.format(lr.score(X_test, y_test)*100))

Testing accuracy: 94.73%


In [42]:
nb = MultinomialNB()
nb.fit(X_train, y_train)

MultinomialNB()

In [43]:
pred = nb.predict(X_test)
pred, y_test

(array([1, 0, 1, ..., 1, 1, 1]), array([1, 0, 1, ..., 1, 1, 1]))

In [44]:
print('Testing accuracy: {:.2f}%'.format(nb.score(X_test, y_test)*100))

Testing accuracy: 93.37%


In [45]:
dt = DecisionTreeRegressor()
dt.fit(X_train, y_train)

DecisionTreeRegressor()

In [46]:
pred = dt.predict(X_test)
pred, y_test

(array([0., 1., 1., ..., 1., 1., 1.]), array([1, 0, 1, ..., 1, 1, 1]))

In [47]:
print('Testing accuracy: {:.2f}%'.format(dt.score(X_test, y_test)*100))

Testing accuracy: 54.07%
